###
GET http://localhost:8080/api/weight/all


###
GET http://localhost:8080/api/weight/2014-09-11T04:33:22

###
POST http://localhost:8080/api/weight/
Content-Type: application/json

{
  "dateRecorded": "2024-02-10T15:00:12.49766",
  "weight": 177.3
}

###
PUT http://localhost:8080/api/weight/2024-02-10T15:00:12.49766
Content-Type: application/json

{
  "dateRecorded": "2024-02-10T15:00:12.49766",
  "weight": 179.3
}

###
DELETE http://localhost:8080/api/weight/2024-02-10T15:00:12.49766
